### ISSUE TITLE
I get an error when I open Flasher, and the error is as follows

### ISSUE THREAD

**Issue by Faith-dotw** [xiv3r/Deauther-RTL8720DN#1]
![屏幕截图 2024-12-24 201159](https://github.com/user-attachments/assets/783742fe-8c41-461e-8787-37ffb935601c)

**Comment by xiv3r** [comment]
Install python3.10

**Comment by Faith-dotw** [comment]
I've installed python3.14 but it still gets an error

**Comment by xiv3r** [comment]
> I've installed python3.14 but it still gets an error

Kindly download the file and flash the firmware
https://codeload.github.com/Arifmaulanaazis/Ereshkigal/zip/refs/heads/V1.0.3

**Comment by Faith-dotw** [comment]
Thanks, he is already usable, can you provide me with the source code I would like to translate it into other languages

**Comment by xiv3r** [comment]
> Thanks, he is already usable, can you provide me with the source code I would like to translate it into other languages


https://github.com/xiv3r/Deauther-RTL8720DN/releases/download/RTL8720DN/RTL8720DN-Deauther.zip
